// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwT9urv-uoJ3h7u7PMnAby7JEiyDoqGQ8',
    appId: '1:20391681275:web:a342b1d0d0877e7c58e45e',
    messagingSenderId: '20391681275',
    projectId: 'fir-d27d1',
    authDomain: 'fir-d27d1.firebaseapp.com',
    storageBucket: 'fir-d27d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGoS-ToycpsvtFWqo-j_0z4zCY7XvtnkQ',
    appId: '1:20391681275:android:539c98186bd261ca58e45e',
    messagingSenderId: '20391681275',
    projectId: 'fir-d27d1',
    storageBucket: 'fir-d27d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_jMHERVlJJdaclr4c39VP8cqo9RTDfEc',
    appId: '1:20391681275:ios:92a53d844f7ae2cc58e45e',
    messagingSenderId: '20391681275',
    projectId: 'fir-d27d1',
    storageBucket: 'fir-d27d1.appspot.com',
    iosClientId: '20391681275-340fr618v1ejjq3s5mf1tka7csvmtrnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_jMHERVlJJdaclr4c39VP8cqo9RTDfEc',
    appId: '1:20391681275:ios:59fac77efa7aa7af58e45e',
    messagingSenderId: '20391681275',
    projectId: 'fir-d27d1',
    storageBucket: 'fir-d27d1.appspot.com',
    iosClientId: '20391681275-q92tfd7sr46vsr188eid1606c62h1nvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
